// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iTracker
{
    public partial class TrackingView : UIView
    {
        public TrackingView(IntPtr handle) : base(handle)
        {

        }

        public override void DrawRect(CoreGraphics.CGRect area, UIViewPrintFormatter formatter)
        {
            base.DrawRect(area, formatter);

            //draw circle

        }
    }
}
